trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '18.x'
  buildOutput: 'dist'   # change if your app uses a different folder

stages:

# -----------------------
# BUILD STAGE
# -----------------------
- stage: Build
  displayName: Build Node Backend
  jobs:
  - job: BuildJob
    displayName: Install, Test, Build
    steps:

    # Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: Install Node.js

    # Install dependencies
    - script: npm install
      displayName: Install Dependencies


    # Copy files to artifact staging
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          $(buildOutput)/**
          package.json
          package-lock.json
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: Prepare Artifact

    # Publish artifact (for Release pipeline)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: Publish Artifact